// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNJAOL6aYD14b9X1BGJRz_GiSccTqvFA4',
    appId: '1:181733606198:web:3f0f3b1a47273e05e62997',
    messagingSenderId: '181733606198',
    projectId: 'chat-app-98b9c',
    authDomain: 'chat-app-98b9c.firebaseapp.com',
    storageBucket: 'chat-app-98b9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxW_7XhmLlW3KA2qQd1_gWPdA1-CkFokU',
    appId: '1:181733606198:android:575273df39c1bf89e62997',
    messagingSenderId: '181733606198',
    projectId: 'chat-app-98b9c',
    storageBucket: 'chat-app-98b9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHIDxXRvhFtm5xnE6atZ8_zIuW1cBsS4k',
    appId: '1:181733606198:ios:ef7f3601402d03aee62997',
    messagingSenderId: '181733606198',
    projectId: 'chat-app-98b9c',
    storageBucket: 'chat-app-98b9c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHIDxXRvhFtm5xnE6atZ8_zIuW1cBsS4k',
    appId: '1:181733606198:ios:ef7f3601402d03aee62997',
    messagingSenderId: '181733606198',
    projectId: 'chat-app-98b9c',
    storageBucket: 'chat-app-98b9c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNJAOL6aYD14b9X1BGJRz_GiSccTqvFA4',
    appId: '1:181733606198:web:5e9ffe37634b0fcce62997',
    messagingSenderId: '181733606198',
    projectId: 'chat-app-98b9c',
    authDomain: 'chat-app-98b9c.firebaseapp.com',
    storageBucket: 'chat-app-98b9c.firebasestorage.app',
  );
}
